#!/bin/bash

# Nombre:	download-updates.sh
# Autor:	Charlie Martínez® <cmartinez@quirinux.org>
# Licencia:	https://www.gnu.org/licenses/gpl-3.0.txt
# Descripción:	Descarga script de actualizaciones
# Versión:	1.0

FILE="/usr/local/bin/updates"

if [ -e ${FILE} ]; then

sudo rm /usr/local/bin/updates

fi 

sudo wget --no-check-certificate 'https://www.quirinux.org/updates/updates' -O /usr/local/bin/updates
sudo chmod 775 /usr/local/bin/updates

